#!/bin/bash - 
#===============================================================================
#
#          FILE: vidlen
# 
#===============================================================================


# standard settings ---------

defaultFlag='-a'
absolutePaths='on' # on/off
durationEmptyDisplayError='on'

# ---------------------------


RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
MAGENTA='\033[1;35m'
CYAN='\033[1;36m'
WHITE='\033[1;37m'
red='\033[1;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
magenta='\033[0;35m'
cyan='\033[0;36m'
white='\033[0;37m'
NC='\033[0m'


function allVids(){
	relativePath=${1:-'./'}
	if [[ "$absolutePaths" == on ]];then
		if [[ "$relativePath" != '/'* ]];then
			relativePath="${PWD}/${relativePath}"
		fi
	fi

	vidFileExists='no'
	while read file
	do
		is_vid='false'
		for extension in .avi .flv .mkv .mp4 .mov .webm
		do
			if [[ "$file" == *"$extension" ]]
			then
				is_vid='true'
				vidFileExists='yes'
				break
			fi
		done
		if [[ "$is_vid" == 'true' ]]
		then
			vidFile="$file"
			Output=$(ffprobe "$vidFile" 2>&1)
			Duration=$(grep -o -E 'Duration\: ([0-9]{2}:){2}([0-9]{2}|\.)+' <<< "$Output")

			if [[ "$durationEmptyDisplayError" == on ]];then
				if [[ "$Duration" == '' ]];then
					Duration="${RED}no-duration${NC}"
				fi
			fi

			#printf "${CYAN}\'${vidFile}\'${NC}   →   ${WHITE}${Duration}${NC}\n"
			output+=("${CYAN}\'${vidFile}\'${NC}   →   ${WHITE}${Duration}${NC}\n")
		fi
	done< <(ls "${relativePath}")


  ## printing results
	if [[ "$vidFileExists" == 'yes' ]]
	then
		printf "${BLUE}length of given vid-files:\n${WHITE}---${NC}\n"
		
		lineAmount=${#output[@]}
		nowPrinting=0
		while [ "$nowPrinting" -le "$lineAmount" ]
		do
			printf "${output[$nowPrinting]}"
			nowPrinting=$((nowPrinting + 1))
		done

		printf "${WHITE}---${NC}\n"
	else
		printf "${RED} No video files found in directory: ${WHITE}'${relativePath}'${NC}\n"
		exit 1
	fi

}

function singleVid(){
	vidFile="$1"
	Output=$(ffprobe "$vidFile" 2>&1)
	Duration=$(grep -o -E 'Duration\: ([0-9]{2}:){2}([0-9]{2}|\.)+' <<< "$Output")

	if [[ "$durationEmptyDisplayError" == on ]];then
		if [[ "$Duration" == '' ]];then
			Duration="${RED}no-duration${NC}"
		fi
	fi

	printf "${BLUE}length of ${CYAN}\'${vidFile}\'${BLUE}:\n${WHITE}---${NC}\n"
	printf "${WHITE}${Duration}${NC}\n"
	printf "${WHITE}---${NC}\n"
}

flag=${1:-${defaultFlag}}

# TODO check, what argument is (relative path, flag, file, …)

if [[ "$flag" == "-"* ]];then
	if [[ "$flag" == '-a' || "$flag" == '--all' ]];then
		flag=$1
		shift 1
		if [[ "$#" == 0 ]];then
			# TODO add relative path here as argument
			allVids
		elif [[ "$#" > 0 ]];then
			allVids "$1"
		fi
	else
		printf "unkonw flag ${WHITE}$1${NC}\n"
	fi
else
	singleVid "$1"
fi

